### ISSUE TITLE
Layer control disappears when switching to new sample unit

### ISSUE THREAD

**Issue by ktarrio** [parevalo/tstools_online#22]
Pulled the latest version of the tool a few days ago (w/ Clicked TS point) but the toggle layers button in the upper right for clicked Landsat images has disappeared..

**Comment by parevalo** [comment]
I don't know what you mean. I see the layer control in the upper right side of the map and I can successfully toggle them on an on. I just downloaded the version currently available on the master branch here.

**Comment by parevalo** [comment]
Also, since repos can change constantly (I just pushed a new update a second ago), including the commit, release or tab that you are using can make it easier to diagnose the issue. We haven't started using tags or releases (I need to learn how to properly use those) but you can always see your current commit by typing 'git log' to check what the latest commit is. You can reference the whole commit name here, or just the first 7 characters.

**Comment by ktarrio** [comment]
<img width="2032" alt="updated_tstools" src="https://user-images.githubusercontent.com/44216276/54617923-87e3fb80-4a38-11e9-99cd-fd738d17a8f4.png">
<img width="568" alt="branch_status" src="https://user-images.githubusercontent.com/44216276/54617931-8adeec00-4a38-11e9-930c-2951d77b34c6.png">

**Comment by ktarrio** [comment]
Most recent commit:
<img width="563" alt="most_recent_commit" src="https://user-images.githubusercontent.com/44216276/54618114-d85b5900-4a38-11e9-8a77-17a5f9615817.png">

**Comment by parevalo** [comment]
There have been a ton of changes since that version, pull the latest version from master. I tested it yesterday and worked well.

**Comment by ktarrio** [comment]
Should have mentioned that the toggle function appears when I first run everything but disappears _after_ I load a point!

**Comment by parevalo** [comment]
I cannot replicate your behavior with my dataset, I'll have to check with you directly again.

**Comment by parevalo** [comment]
Seems to affect only installations with ipyleaflet >=0.9.2. If widgets are re-displayed the layer control reappears.
